name: EBAC CI
on: 
  push:
    branches: [ci]
  workflow_dispatch:
jobs:
  test:
    runs-on: unbutu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - name: cypress run
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with: 
          install-comando: npm install
          browser: chrome
